export interface JharkhandDistrict {
  id: string;
  name: string;
  hindiName: string;
  headquarters: string;
  division: string;
  majorBlocks: string[];
  ulbs: string[];
}

export const JHARKHAND_DISTRICTS: JharkhandDistrict[] = [
  {
    id: "ranchi",
    name: "Ranchi",
    hindiName: "राँची",
    headquarters: "Ranchi",
    division: "South Chotanagpur",
    majorBlocks: ["Kanke", "Doranda", "Namkum", "Ormanjhi", "Ratu", "Mandard", "Bero", "Itki", "Siladon"],
    ulbs: ["Ranchi Municipal Corporation (RMC)", "Bundu Nagar Panchayat"],
  },
  {
    id: "dhanbad",
    name: "Dhanbad",
    hindiName: "धनबाद",
    headquarters: "Dhanbad",
    division: "North Chotanagpur",
    majorBlocks: ["Jharia", "Baghmara", "Bank More", "Govindpur", "Nirsa", "Tundi", "Topchanchi"],
    ulbs: ["Dhanbad Municipal Corporation (DMC)", "Chirkunda Nagar Parishad"],
  },
  {
    id: "east_singhbhum",
    name: "East Singhbhum (Jamshedpur)",
    hindiName: "पूर्वी सिंहभूम (जमशेदपुर)",
    headquarters: "Jamshedpur",
    division: "Kolhan",
    majorBlocks: ["Bistupur", "Golmuri", "Mango", "Jugsalai", "Potka", "Ghatshila", "Chakulia", "Baharagora"],
    ulbs: ["Jamshedpur Notified Area Committee (JNAC)", "Mango Municipal Corporation", "Jugsalai Municipal Council"],
  },
  {
    id: "bokaro",
    name: "Bokaro",
    hindiName: "बोकारो",
    headquarters: "Bokaro Steel City",
    division: "North Chotanagpur",
    majorBlocks: ["Chas", "Bermo", "Chandrapura", "Gomia", "Jaridih", "Nawadih", "Peterwar", "Kasmar"],
    ulbs: ["Chas Municipal Corporation", "Phusro Nagar Parishad"],
  },
  {
    id: "hazaribagh",
    name: "Hazaribagh",
    hindiName: "हजारीबाग",
    headquarters: "Hazaribagh",
    division: "North Chotanagpur",
    majorBlocks: ["Hazaribagh Sadar", "Matwari", "Barhi", "Chorparan", "Ichak", "Katkamsandi", "Keradari", "Bishnugarh"],
    ulbs: ["Hazaribagh Municipal Corporation"],
  },
  {
    id: "deoghar",
    name: "Deoghar",
    hindiName: "देवघर",
    headquarters: "Deoghar",
    division: "Santhal Pargana",
    majorBlocks: ["Deoghar Sadar", "Mohanpur", "Sarwan", "Sarath", "Palojori", "Devipur", "Madhupur", "Margomunda"],
    ulbs: ["Deoghar Municipal Corporation", "Madhupur Nagar Parishad"],
  },
  {
    id: "giridih",
    name: "Giridih",
    hindiName: "गिरिडीह",
    headquarters: "Giridih",
    division: "North Chotanagpur",
    majorBlocks: ["Giridih Sadar", "Dumri", "Bagodar", "Gandey", "Jamua", "Deori", "Dhanwar", "Tisri", "Pirtand"],
    ulbs: ["Giridih Municipal Corporation"],
  },
  {
    id: "ramgarh",
    name: "Ramgarh",
    hindiName: "रामगढ़",
    headquarters: "Ramgarh Cantonment",
    division: "North Chotanagpur",
    majorBlocks: ["Ramgarh Sadar", "Patratu", "Gola", "Mandu", "Dulmi", "Chitarpur"],
    ulbs: ["Ramgarh Cantonment Board"],
  },
  {
    id: "dumka",
    name: "Dumka",
    hindiName: "दुमका",
    headquarters: "Dumka",
    division: "Santhal Pargana",
    majorBlocks: ["Dumka Sadar", "Jama", "Jarmundi", "Kathikund", "Shikaripara", "Ranishwar", "Saraiyahat", "Masalia"],
    ulbs: ["Dumka Nagar Parishad"],
  },
  {
    id: "palamu",
    name: "Palamu",
    hindiName: "पलामू",
    headquarters: "Medininagar (Daltonganj)",
    division: "Palamu",
    majorBlocks: ["Medininagar Sadar", "Hussainabad", "Chhatarpur", "Bishrampur", "Lesliganj", "Panki", "Patan", "Hariharganj"],
    ulbs: ["Medininagar Municipal Corporation", "Hussainabad Nagar Panchayat"],
  },
  {
    id: "west_singhbhum",
    name: "West Singhbhum",
    hindiName: "पश्चिमी सिंहभूम",
    headquarters: "Chaibasa",
    division: "Kolhan",
    majorBlocks: ["Chaibasa Sadar", "Chakradharpur", "Jhinkpani", "Khuntpani", "Manjhari", "Tanto", "Jagannathpur", "Noamundi"],
    ulbs: ["Chaibasa Nagar Parishad", "Chakradharpur Nagar Parishad"],
  },
  {
    id: "garhwa",
    name: "Garhwa",
    hindiName: "गढ़वा",
    headquarters: "Garhwa",
    division: "Palamu",
    majorBlocks: ["Garhwa Sadar", "Nagar Untari", "Ranka", "Majhiaon", "Meral", "Bhandaria", "Bhawnathpur", "Dandai"],
    ulbs: ["Garhwa Nagar Parishad", "Nagar Untari Nagar Panchayat"],
  },
  {
    id: "chatra",
    name: "Chatra",
    hindiName: "चतरा",
    headquarters: "Chatra",
    division: "North Chotanagpur",
    majorBlocks: ["Chatra Sadar", "Itkhori", "Hunterganj", "Simaria", "Tandwa", "Pratapda", "Lawalong", "Gidhaur"],
    ulbs: ["Chatra Nagar Parishad"],
  },
  {
    id: "koderma",
    name: "Koderma",
    hindiName: "कोडरमा",
    headquarters: "Koderma",
    division: "North Chotanagpur",
    majorBlocks: ["Koderma Sadar", "Jhumri Telaiya", "Jainagar", "Chandwara", "Markacho", "Satgawan"],
    ulbs: ["Jhumri Telaiya Nagar Parishad", "Koderma Nagar Panchayat"],
  },
  {
    id: "sahibganj",
    name: "Sahibganj",
    hindiName: "साहिबगंज",
    headquarters: "Sahibganj",
    division: "Santhal Pargana",
    majorBlocks: ["Sahibganj Sadar", "Rajmahal", "Borio", "Barhait", "Taljhari", "Pathna", "Mandro"],
    ulbs: ["Sahibganj Nagar Parishad", "Rajmahal Nagar Panchayat"],
  },
  {
    id: "pakur",
    name: "Pakur",
    hindiName: "पाकुड़",
    headquarters: "Pakur",
    division: "Santhal Pargana",
    majorBlocks: ["Pakur Sadar", "Hiranpur", "Littipara", "Amrapara", "Maheshpur", "Pakuria"],
    ulbs: ["Pakur Nagar Parishad"],
  },
  {
    id: "jamtara",
    name: "Jamtara",
    hindiName: "जामताड़ा",
    headquarters: "Jamtara",
    division: "Santhal Pargana",
    majorBlocks: ["Jamtara Sadar", "Narayanpur", "Karmatar", "Mihijam", "Kundhit", "Fatehpur"],
    ulbs: ["Jamtara Nagar Panchayat", "Mihijam Nagar Parishad"],
  },
  {
    id: "latehar",
    name: "Latehar",
    hindiName: "लातेहार",
    headquarters: "Latehar",
    division: "Palamu",
    majorBlocks: ["Latehar Sadar", "Chandwa", "Balumath", "Manika", "Barwadih", "Mahuadanr", "Herhanj"],
    ulbs: ["Latehar Nagar Panchayat"],
  },
  {
    id: "simdega",
    name: "Simdega",
    hindiName: "सिमडेगा",
    headquarters: "Simdega",
    division: "South Chotanagpur",
    majorBlocks: ["Simdega Sadar", "Kolebira", "Bano", "Jaldega", "Thethaitangar", "Bolba", "Kurdeg", "Bansjor"],
    ulbs: ["Simdega Nagar Parishad"],
  },
  {
    id: "khunti",
    name: "Khunti",
    hindiName: "खूंटी",
    headquarters: "Khunti",
    division: "South Chotanagpur",
    majorBlocks: ["Khunti Sadar", "Murhu", "Torpa", "Rania", "Karra", "Arki"],
    ulbs: ["Khunti Nagar Panchayat"],
  },
  {
    id: "lohardaga",
    name: "Lohardaga",
    hindiName: "लोहरदगा",
    headquarters: "Lohardaga",
    division: "South Chotanagpur",
    majorBlocks: ["Lohardaga Sadar", "Kudo", "Kero", "Bhandra", "Senha", "Peshrar"],
    ulbs: ["Lohardaga Nagar Parishad"],
  },
  {
    id: "saraikela_kharsawan",
    name: "Saraikela Kharsawan",
    hindiName: "सरायकेला खरसावां",
    headquarters: "Saraikela",
    division: "Kolhan",
    majorBlocks: ["Saraikela Sadar", "Kharsawan", "Adityapur", "Gamharia", "Chandil", "Ichagarh", "Kukru", "Nimdih"],
    ulbs: ["Adityapur Municipal Corporation", "Saraikela Nagar Panchayat"],
  },
  {
    id: "godda",
    name: "Godda",
    hindiName: "गोड्डा",
    headquarters: "Godda",
    division: "Santhal Pargana",
    majorBlocks: ["Godda Sadar", "Pathargama", "Basantrai", "Mahagama", "Meherma", "Boarijor", "Sundarpahari", "Poreyahat"],
    ulbs: ["Godda Nagar Parishad"],
  },
  {
    id: "gumla",
    name: "Gumla",
    hindiName: "गुमला",
    headquarters: "Gumla",
    division: "South Chotanagpur",
    majorBlocks: ["Gumla Sadar", "Chainpur", "Bishunpur", "Raidih", "Palkot", "Basia", "Kamdara", "Sisai", "Berno"],
    ulbs: ["Gumla Nagar Parishad"],
  },
];

export interface EmergencyContact {
  id: string;
  title: string;
  hindiTitle: string;
  number: string;
  category: "police" | "medical" | "women_child" | "disaster" | "gov_helpline" | "legal_aid";
  department: string;
  officialUrl?: string;
  lastVerifiedDate: string;
  description: string;
  availableHours: string;
}

export const OFFICIAL_EMERGENCY_CONTACTS: EmergencyContact[] = [
  {
    id: "national-emergency-112",
    title: "National Emergency Unified Response Number",
    hindiTitle: "राष्ट्रीय आपातकालीन सहायता नंबर",
    number: "112",
    category: "police",
    department: "Jharkhand Police & Fire Emergency Services",
    officialUrl: "https://jhpolice.gov.in",
    lastVerifiedDate: "2025-05-01",
    description: "24x7 Toll-free single emergency number for Police, Fire, and Medical assistance in Jharkhand.",
    availableHours: "24/7",
  },
  {
    id: "women-helpline-181",
    title: "Jharkhand Women Helpline",
    hindiTitle: "झारखंड महिला हेल्पलाइन",
    number: "181",
    category: "women_child",
    department: "Department of Women, Child Development & Social Security, Govt of Jharkhand",
    officialUrl: "https://wcd.jharkhand.gov.in",
    lastVerifiedDate: "2025-05-01",
    description: "Emergency rescue, legal counseling, and support for women facing distress, violence, or harassment.",
    availableHours: "24/7",
  },
  {
    id: "ambulance-108",
    title: "National Health Mission Emergency Ambulance Services",
    hindiTitle: "108 आपातकालीन एम्बुलेंस सेवा",
    number: "108",
    category: "medical",
    department: "Health, Medical Education & Family Welfare Dept, Jharkhand",
    officialUrl: "https://jharkhandhealth.nic.in",
    lastVerifiedDate: "2025-05-01",
    description: "Free emergency ambulance transport to nearest Sub-divisional, District, or RIMS Medical College.",
    availableHours: "24/7",
  },
  {
    id: "childline-1098",
    title: "Child Emergency Protection Helpline",
    hindiTitle: "चाइल्डलाइन 1098 बाल सुरक्षा हेल्पलाइन",
    number: "1098",
    category: "women_child",
    department: "Jharkhand State Child Protection Society (JSCPS)",
    officialUrl: "https://childlineindia.org",
    lastVerifiedDate: "2025-05-01",
    description: "Emergency support for children needing care, protection, rescue from child labor, or abandonment.",
    availableHours: "24/7",
  },
  {
    id: "cm-helpline-181",
    title: "Jharkhand Chief Minister Grievance Jansamvad Helpline",
    hindiTitle: "मुख्यमंत्री जनसंवाद हेल्पलाइन",
    number: "181",
    category: "gov_helpline",
    department: "Department of Personnel, Administrative Reforms & Rajbhasha",
    officialUrl: "https://cm.jharkhand.gov.in",
    lastVerifiedDate: "2025-05-01",
    description: "Official public grievance portal helpline for escalation of unaddressed municipal & administrative issues.",
    availableHours: "8:00 AM - 8:00 PM",
  },
  {
    id: "disaster-1070",
    title: "State Disaster Management Authority Control Room",
    hindiTitle: "राज्य आपदा प्रबंधन नियंत्रण कक्ष",
    number: "1070",
    category: "disaster",
    department: "Revenue & Disaster Management Dept, Govt of Jharkhand",
    officialUrl: "https://disaster.jharkhand.gov.in",
    lastVerifiedDate: "2025-05-01",
    description: "Flood, lightning strike, forest fire, storm, and disaster relief control helpline.",
    availableHours: "24/7",
  },
  {
    id: "fire-101",
    title: "Jharkhand Fire Emergency Control Room",
    hindiTitle: "दमकल आपातकालीन सेवा 101",
    number: "101",
    category: "police",
    department: "Jharkhand Fire Services HQ, Ranchi",
    officialUrl: "https://jhpolice.gov.in/fire",
    lastVerifiedDate: "2025-05-01",
    description: "Immediate dispatch for residential, commercial, or forest fire emergencies.",
    availableHours: "24/7",
  },
  {
    id: "legal-aid-15100",
    title: "Jharkhand State Legal Services Authority (JHALSA)",
    hindiTitle: "झाल्सा नि:शुल्क कानूनी सहायता",
    number: "15100",
    category: "legal_aid",
    department: "JHALSA High Court Campus, Ranchi",
    officialUrl: "https://jhalsa.jharkhand.gov.in",
    lastVerifiedDate: "2025-05-01",
    description: "Free legal aid, advocate assignment, and Lok Adalat assistance for economically weaker sections & ST/SC citizens.",
    availableHours: "9:30 AM - 6:00 PM",
  },
];

